### ISSUE TITLE
Improvement suggestion in README file, a confusing detail.

### ISSUE THREAD

**Issue by manorie** [zeantsoi/GoogleBooks#21]
The part below needs to be modified. The usage must be like book.sale_info['listPirce']['amount'] . I seen that you have explained in top but the code view must be changed, I found the usage after checking the source code. Thx for this gem btw, I saved couple hours ! :)

Sale and retail information is available on some volumes as of Google Books API v1. GoogleBooks returns a hash of these attributes (where available) under the sale_info attribute.

~~~ruby
book = GoogleBooks.search(9780345508553).first # Do Androids Dream of Electric Sheep?

book['country'] #=> 'US'
book['saleability'] #=> 'FOR_SALE'
book['isEbook'] #=> true
book['listPrice']['amount'] #=> 9.99
book['listPrice']['currencyCode'] #=> 'USD'
book['retailPrice']['amount'] #=> 9.99
book['retailPrice']['currencyCode'] #=> 'USD'
book['buyLink'] #=> 'http://books.google.com/books?.
~~~

**Comment by zeantsoi** [comment]
Resolved with PR #22.
